- name: install package by apt
  remote_user: root
  when: ansible_distribution == "Ubuntu"
  ansible.builtin.apt:
    name: "{{ package_name }}"
- name: install git package by yum
  remote_user: root
  when: ansible_distribution == "CentOS"
  ansible.builtin.yum:
    name: "{{ package_name }}"

