version: "3"
services: 
  redmine: 
    image: redmine
    ports: 
      - 8080:3000
    environment:
      REDMINE_DB_PASSWORD: 12345
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_POSTGRES: db


  db: 
    image: postgres
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: redmine 
      POSTGRES_PASSWORD: 12345

