- hosts: webservers,appservers
  remote_user: root 
  vars:
    usernames: [ "damire"]
  tasks:
    - name: create users
      remote_user: root
      tags: ["user setup"]
      ansible.builtin.user:
        name: "{{ item }}"
      loop: "{{ usernames }}" 
    - name: set public key
      remote_user: root
      tags: ["user setup"]
      ansible.builtin.copy:
        src: "./files/authorized_keys"
        dest: "/home/{{ item }}/.ssh/"
      loop: "{{ usernames }}"
    - name: install git package by apt
      remote_user: root
      tags: ["git"]
      when: ansible_distribution == "Ubuntu"
      ansible.builtin.apt:
        name: git
    - name: install git package by yum
      remote_user: root
      tags: ["git"]
      when: ansible_distribution == "CentOS"
      ansible.builtin.yum:
        name: git

    - name: set git config 
      remote_user: root
      tags: ["git"]
      ansible.builtin.template:
        src:  ./.gitconfig
        dest: "/home/{{ item }}/.gitconfig"
      loop: "{{ usernames }}"
    
