- hosts: webservers
  gather_facts: false
  vars:
    username: tirion
  tasks: 
    - name: create user
      remote_user: root
      ansible.builtin.user:
        name: "{{ username }}"
        groups: 
          - sudo
    - name: set ssh keys
      remote_user: root
      ansible.posix.authorized_key:
        user: "{{ username }}"
        key: "{{ lookup('file', '../files/key.pub') }} "
    - name: install python
      remote_user: root 
      ansible.builtin.apt:
        name: python3
    - name: run server
      tags: ["server"]
      remote_user: "{{ username }}"
      register: result
      ansible.builtin.shell:
        cmd: "python3 -m http.server 8000 --bind 127.0.0.1 > /tmp/log.txt 2>&1 &" 
    - name: debug
      ansible.builtin.debug:
        msg: "{{ result }}"
