- name: install git
  tags: "git"
  remote_user: root
  ansible.builtin.import_tasks:
    file: package_install_playbook.yaml  
  vars: 
    package_name: "git"      
- name: set git config 
  remote_user: root
  tags: ["git"]
  ansible.builtin.template:
    src:  "../files/.gitconfig"
    dest: "/home/{{ item }}/.gitconfig"
  loop: "{{ usernames }}"
