- hosts: webservers
  gather_facts: no
  tasks:
    - name: install nginx
      remote_user: root
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes
    - name: update nginx config
      remote_user: root
      tags: ["nginx config"]
      ansible.builtin.copy:
        src: ./index.html
        dest: /usr/share/nginx/html/index.html
      notify:
        - restart nginx
    - name: update nginx config
      tags: ["nginx config"]
      remote_user: root
      ansible.builtin.copy:
        src: ./nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      remote_user: root
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
