- hosts: webservers
  gather_facts: no
  vars: 
    path_to_static: "/var/www/public_html" 
  tasks:
    - name: create file structure
      remote_user: root
      ansible.builtin.file:
        state: directory
        path: "{{ path_to_static }}"
    - name: create index.html
      remote_user: root
      ansible.builtin.copy:
        content: "Hello, Hexlet!"
        dest: "{{ path_to_static }}/index.html"
        mode: '755'
    - name: install python
      remote_user: root
      ansible.builtin.apt:
        name: python3
    - name: run server
      remote_user: root
      ansible.builtin.shell:
        cmd: "python3 -m http.server 8000 --bind 127.0.0.1 --directory {{ path_to_static }}"
    
