- hosts: webservers
  remote_user: root
  gather_facts: no
  vars:
    username: damire
  tasks:
    - name: create user
      ansible.builtin.user:
        name: "{{ username }}"
        
    - name: set ssh key
      tags: ["ssh keys"]
      ansible.posix.authorized_key:
        user: "{{ username }}"
        key: "{{ lookup('file', '../files/key.pub') }} "
