- hosts: appservers
  vars: 
    packages: ["nginx", "epel-release" ,"cowsay"] 
  tasks: 
    - name: package installation
      remote_user: root
      ansible.builtin.dnf:
        name: "{{ item }}"
      loop: "{{ packages }}"
    - name: register cowsay
      ansible.builtin.command: "cowsay \" This is server {{ ansible_hostname  }}\""
      register: cowsay_result

    - name: update nginx html
      remote_user: root
      tags: ["nginx config"]
      ansible.builtin.template: 
        src: ./index.html
        dest: /usr/share/nginx/html/index.html
      notify: 
        - restart nginx
    - name: update nginx.conf
      remote_user: root    
      tags: ["nginx config"]
      ansible.builtin.template:
        src: ./nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: 
        - restart nginx
  handlers:    
    - name: restart nginx
      remote_user: root 
      ansible.builtin.service:
        name: nginx
        state: reloaded 


