---
- name: infra
  hosts: webservers 
  gather_facts: no
  tasks:
    - name: install redis server
      remote_user: root 
      ansible.builtin.apt:
        name: redis-server
        state: present
        update_cache: yes 
    - name: remove redis server
      remote_user: root 
      ansible.builtin.apt:
        name: redis-server
        state: absent
    - name: install git 
      remote_user: root
      ansible.builtin.apt:
        name: git 
        state: present
        update_cache: yes
    - name: check git version
      remote_user: root
      ansible.builtin.command:
        cmd: "git --version"  
