- hosts: webservers
  gather_facts: no
  vars:
    usernames: ["jaime", "sansa", "robert"]
  tasks:
    - name: create users
      remote_user: root
      tags: ["user setup"]
      ansible.builtin.user:
        name: "{{ item }}"
      loop: "{{ usernames }}" 
    - name: set public key
      remote_user: root
      tags: ["user setup"]
      ansible.builtin.copy:
        src: "./files/authorized_keys"
        dest: "/home/{{ item }}/.ssh/"
      loop: "{{ usernames }}"
    - name: install packages 
      remote_user: root
      tags: ["git"] 
      ansible.builtin.apt:
        name: git
    - name: set git config 
      remote_user: root
      tags: ["git"]
      ansible.builtin.template:
        src:  ./.gitconfig
        dest: "/home/{{ item }}/.gitconfig"
      loop: "{{ usernames }}"
    
